name: Build and deploy to Screeps

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    name: Pack into single file
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js to build
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - run: npm ci
      - run: npm run build --if-present
      - run: npm test
        env:
          CI: true
      - name: Upload artifact
        uses: actions/upload-artifact@v1.0.0
        with:
          # Artifact name
          name: main
          # Directory containing files to upload
          path: dist/main.js